MODULE CYCAS_OUTPUT_COMPONENT
USE BASIC_DATA
USE DRAW
USE OUTPUT_PARAMETERS
IMPLICIT NONE
PRIVATE

PUBLIC :: INITIAL_OUTPUT
PUBLIC :: OUTPUT_COREMAPS
PUBLIC :: OUTPUT_CASES

CONTAINS

    SUBROUTINE INITIAL_OUTPUT(CHA_LNK_HEAD)
        IMPLICIT NONE
        TYPE(MATRIX_OF_CHA_NODE), POINTER, INTENT(IN OUT) :: CHA_LNK_HEAD
        INTEGER(NM_INT) :: I, J, K

        IF (.NOT. ASSOCIATED(CHA_LNK_HEAD)) THEN
            ALLOCATE(CHA_LNK_HEAD)
            ALLOCATE(CHA_LNK_HEAD%CONTENT)
        END IF

        CHA_LNK_HEAD%CONTENT%COLUMN = LARGE_LOGO_COLUMN
        CHA_LNK_HEAD%CONTENT%ROW = LARGE_LOGO_ROW
        ALLOCATE(CHA_LNK_HEAD%CONTENT%MATRIX(CHA_LNK_HEAD%CONTENT%COLUMN, CHA_LNK_HEAD%CONTENT%ROW))
        
        DO I = 1, CHA_LNK_HEAD%CONTENT%ROW
            DO J = 1, CHA_LNK_HEAD%CONTENT%COLUMN
                K = (I - 1) * CHA_LNK_HEAD%CONTENT%COLUMN + J
                CHA_LNK_HEAD%CONTENT%MATRIX(J, I) = LARGE_LOGO(K : K)
            END DO
        END DO
    END SUBROUTINE INITIAL_OUTPUT

    SUBROUTINE OUTPUT_COREMAPS(ASSEMBLY_DIS_A, ROD_DIS_A, RDGP_DIS_A, CHA_MATR_LNK, NAME_LIST, VALUE_LIST, LIST_LENGTH)
        IMPLICIT NONE
        TYPE(STR_MATRIX),   TARGET, ALLOCATABLE,     INTENT(IN)     :: ASSEMBLY_DIS_A(:)
        TYPE(STR_MATRIX),   TARGET, ALLOCATABLE,     INTENT(IN)     :: ROD_DIS_A(:)
        TYPE(STR_MATRIX),   TARGET, ALLOCATABLE,     INTENT(IN)     :: RDGP_DIS_A(:)
        TYPE(MATRIX_OF_CHA_NODE),   POINTER,         INTENT(IN OUT) :: CHA_MATR_LNK
        TYPE(POINTER_ARRAY_OF_STR), ALLOCATABLE,     INTENT(IN)     :: NAME_LIST(:)
        TYPE(POINTER_ARRAY_OF_STR), ALLOCATABLE,     INTENT(IN)     :: VALUE_LIST(:)
        INTEGER(NM_INT),                            INTENT(IN)     :: LIST_LENGTH
        
        TYPE(STR_MATRIX),         POINTER :: ASSEMBLY_DIS(:) => NULL()
        TYPE(STR_MATRIX),         POINTER :: ROD_DIS(:) => NULL()
        TYPE(STR_MATRIX),         POINTER :: RDGP_DIS(:) => NULL()
        TYPE(MATRIX_OF_CHA_NODE), POINTER :: PTR => NULL()
        TYPE(MATRIX_OF_CHA),      POINTER :: LABLE_OUT => NULL()
        TYPE(MATRIX_OF_CHA),      POINTER :: CORE_PRINT_ASSEMBLY_DIS => NULL()
        TYPE(MATRIX_OF_CHA),      POINTER :: CORE_PRINT_ROD_DIS => NULL()
        TYPE(MATRIX_OF_CHA),      POINTER :: CORE_PRINT_RDGROUP_DIS => NULL()
        INTEGER(NM_INT), PARAMETER       :: CORE_PRINT_DIMENSION = 1
        LOGICAL,          PARAMETER       :: CORE_PRINT_MESH_ON = .FALSE.
        TYPE(ARRAY_OF_STR),       POINTER :: STR_PTR => NULL()
        INTEGER(NM_INT)                  :: I
        INTEGER(NM_INT)                  :: STEP_BACK
        CHARACTER                         :: EQ_SIGN

        ASSEMBLY_DIS => ASSEMBLY_DIS_A
        ROD_DIS      => ROD_DIS_A
        RDGP_DIS     => RDGP_DIS_A
        ! INITIAL CURRENT NODE POINTER
        PTR=>CHA_MATR_LNK
        ! |-> FOR BLOCK LABLE
        CALL CPY_ARY_OF_STR(STR_PTR, LABLE_0005)
        CALL GENERATE_LABLE(STR_PTR, LABLE_OUT)
        CALL APPEND_AFTER_MAT_CHA_LINK(PTR, LABLE_OUT)
        ! FOR BLOCK LABLE <-|
        ! FOR RETURN LINES
        I = 2
        CALL INSERT_RETURN(I, PTR)

        ! FOR CORE MAP LABLE
        STEP_BACK = 2
        CALL CPY_ARY_OF_STR(STR_PTR, LABLE_0001)
        CALL INSERT_STRING(STR_PTR, PTR, STEP_BACK)

        ! |-> FOR ASSEMBLY MAP
        STEP_BACK = 4
        CALL CPY_ARY_OF_STR(STR_PTR, LABLE_0002)
        CALL INSERT_STRING(STR_PTR, PTR, STEP_BACK)
        NULLIFY(CORE_PRINT_ASSEMBLY_DIS)
        CALL CORE_VIEW_RADIAL_ASSEMBLY(ASSEMBLY_DIS, CORE_PRINT_DIMENSION, CORE_PRINT_ASSEMBLY_DIS, CORE_PRINT_MESH_ON)
        CALL APPEND_AFTER_MAT_CHA_LINK(PTR, CORE_PRINT_ASSEMBLY_DIS)
        CALL CPY_ARY_OF_STR(STR_PTR, LABLE_0007)
        CALL INSERT_STRING(STR_PTR, PTR, STEP_BACK)
        ! FOR ASSEMBLY MAP <-|
        ! FOR RETURN LINES
        I = 1
        CALL INSERT_RETURN(I, PTR)

        ! |-> FOR CONTROL ROD MAP
        CALL CPY_ARY_OF_STR(STR_PTR, LABLE_0003)
        CALL INSERT_STRING(STR_PTR, PTR, STEP_BACK)
        NULLIFY(CORE_PRINT_ROD_DIS)
        CALL CORE_VIEW_RADIAL_ASSEMBLY(ROD_DIS, CORE_PRINT_DIMENSION, CORE_PRINT_ROD_DIS, CORE_PRINT_MESH_ON)
        CALL APPEND_AFTER_MAT_CHA_LINK(PTR, CORE_PRINT_ROD_DIS)
        CALL CPY_ARY_OF_STR(STR_PTR, LABLE_0008)
        CALL INSERT_STRING(STR_PTR, PTR, STEP_BACK)
        ! FOR CONTROL ROD MAP <-|
        ! FOR RETURN LINES
        I = 1
        CALL INSERT_RETURN(I, PTR)
        
        ! |-> FOR CONTROL ROD GROUP MAP
        CALL CPY_ARY_OF_STR(STR_PTR, LABLE_0004)
        CALL INSERT_STRING(STR_PTR, PTR, STEP_BACK)
        NULLIFY(CORE_PRINT_RDGROUP_DIS)
        CALL CORE_VIEW_RADIAL_ASSEMBLY(RDGP_DIS, CORE_PRINT_DIMENSION, CORE_PRINT_RDGROUP_DIS, CORE_PRINT_MESH_ON)
        CALL APPEND_AFTER_MAT_CHA_LINK(PTR, CORE_PRINT_RDGROUP_DIS)
        CALL CPY_ARY_OF_STR(STR_PTR, LABLE_0009)
        CALL INSERT_STRING(STR_PTR, PTR, STEP_BACK)
        ! FOR CONTROL ROD GROUP MAP <-|
        
        STEP_BACK = 2
        CALL CPY_ARY_OF_STR(STR_PTR, LABLE_0006)
        CALL INSERT_STRING(STR_PTR, PTR, STEP_BACK)
        
        ! FOR RETURN LINES
        I = 1
        CALL INSERT_RETURN(I, PTR)
        
        ! FOR SYMMETRY PARAMETERS
        STEP_BACK = 2
        CALL CPY_ARY_OF_STR(STR_PTR, LABLE_0010)
        CALL INSERT_STRING(STR_PTR, PTR, STEP_BACK)
        STEP_BACK = 4
        NULLIFY(LABLE_OUT)
        EQ_SIGN = '='
        CALL GENERATE_NAME_VALUE_PAIRS(NAME_LIST, VALUE_LIST, LIST_LENGTH, LABLE_OUT, STEP_BACK, EQ_SIGN)
        CALL APPEND_AFTER_MAT_CHA_LINK(PTR, LABLE_OUT)
        STEP_BACK = 2
        CALL CPY_ARY_OF_STR(STR_PTR, LABLE_0011)
        CALL INSERT_STRING(STR_PTR, PTR, STEP_BACK)
        
        ! SET LINK POINTER TO THE LAST GENERATING NODE IN THIS CALL
        CHA_MATR_LNK => PTR
    END SUBROUTINE OUTPUT_COREMAPS
    
    SUBROUTINE OUTPUT_CASES(CASE_ID, JOB_ID, DATE_TIME, REF_TIME, REF_BU, TITLE, CHA_MATR_LNK, PRINT_OPTION)
        IMPLICIT NONE
        INTEGER,                           INTENT(IN)     :: CASE_ID
        INTEGER,                           INTENT(IN)     :: JOB_ID
        INTEGER, DIMENSION(8),             INTENT(IN)     :: DATE_TIME  ! 1,2,3 AND 5,6,7
        REAL(DP),                          INTENT(IN)     :: REF_TIME
        INTEGER,                           INTENT(IN)     :: REF_BU
        TYPE(ARRAY_OF_STR),                INTENT(IN)     :: TITLE
        TYPE(MATRIX_OF_CHA_NODE), POINTER, INTENT(IN OUT) :: CHA_MATR_LNK
        INTEGER(NM_INT),                  INTENT(IN)     :: PRINT_OPTION

        TYPE(MATRIX_OF_CHA_NODE),   POINTER     :: PTR => NULL()
        TYPE(POINTER_ARRAY_OF_STR), ALLOCATABLE :: TIT_VLIST(:)
        INTEGER(NM_INT)                        :: I, J, K
        CHARACTER(LEN=100)                      :: TEMP               
        
        ALLOCATE(TIT_VLIST(TITLE_ITEM_NUM))
        
        
        
        PTR => CHA_MATR_LNK
        
        ! ############## PREPARE CASE TITLE ############## ->
        ! 1 FOR Version
        ALLOCATE(TIT_VLIST(1)%PTR)
        TIT_VLIST(1)%PTR%LENGTH_OF_STR = LEN(CODE_VERSION)
        ALLOCATE(TIT_VLIST(1)%PTR%STR(TIT_VLIST(1)%PTR%LENGTH_OF_STR))
        DO I = 1, TIT_VLIST(1)%PTR%LENGTH_OF_STR
            TIT_VLIST(1)%PTR%STR(I) = CODE_VERSION(I:I)
        END DO
        
        ! 2 FOR JOB ID
        J = 5
        ALLOCATE(TIT_VLIST(2)%PTR)
        TIT_VLIST(2)%PTR%LENGTH_OF_STR = J
        ALLOCATE(TIT_VLIST(2)%PTR%STR(TIT_VLIST(2)%PTR%LENGTH_OF_STR))
        WRITE(TEMP, '(I5)') JOB_ID
        DO I = 1, TIT_VLIST(2)%PTR%LENGTH_OF_STR
            TIT_VLIST(2)%PTR%STR(I) = TEMP(I:I)
        END DO  
        
        ! 3 FOR Date/Time
        ALLOCATE(TIT_VLIST(3)%PTR)
        !   2017/01/19 13:36:45
        !   2017/ 01/   19B   13:   36:   45
        !   4+1 + 2+1 + 2+1 + 2+1 + 2+1 + 2
        J = 19
        TIT_VLIST(3)%PTR%LENGTH_OF_STR = J
        ALLOCATE(TIT_VLIST(3)%PTR%STR(TIT_VLIST(3)%PTR%LENGTH_OF_STR))
        K = 1
        ! FOR YEAR
        J = 4
        WRITE(TEMP, '(I4)') DATE_TIME(1)
        DO I = 1, J
            TIT_VLIST(3)%PTR%STR(K) = TEMP(I:I)
            K = K + 1
        END DO      
        TIT_VLIST(3)%PTR%STR(K) = '/'
        K = K + 1
        
        ! FOR MONTH
        J = 2
        WRITE(TEMP, '(I2.2)') DATE_TIME(2)
        DO I = 1, J
            TIT_VLIST(3)%PTR%STR(K) = TEMP(I:I)
            K = K + 1
        END DO      
        TIT_VLIST(3)%PTR%STR(K) = '/'
        K = K + 1
        
        ! FOR DAY
        J = 2
        WRITE(TEMP, '(I2.2)') DATE_TIME(3)
        DO I = 1, J
            TIT_VLIST(3)%PTR%STR(K) = TEMP(I:I)
            K = K + 1
        END DO      
        TIT_VLIST(3)%PTR%STR(K) = ' '
        K = K + 1
        
        ! FOR HOUR
        J = 2
        WRITE(TEMP, '(I2.2)') DATE_TIME(5)
        DO I = 1, J
            TIT_VLIST(3)%PTR%STR(K) = TEMP(I:I)
            K = K + 1
        END DO      
        TIT_VLIST(3)%PTR%STR(K) = ':'
        K = K + 1
        
        ! FOR MINUTE
        J = 2
        WRITE(TEMP, '(I2.2)') DATE_TIME(6)
        DO I = 1, J
            TIT_VLIST(3)%PTR%STR(K) = TEMP(I:I)
            K = K + 1
        END DO      
        TIT_VLIST(3)%PTR%STR(K) = ':'
        K = K + 1       
        
        ! FOR SECOND
        J = 2
        WRITE(TEMP, '(I2.2)') DATE_TIME(7)
        DO I = 1, J
            TIT_VLIST(3)%PTR%STR(K) = TEMP(I:I)
            K = K + 1
        END DO
        
        ! 4 FOR Case ID
        J = 4
        ALLOCATE(TIT_VLIST(4)%PTR)
        TIT_VLIST(4)%PTR%LENGTH_OF_STR = J
        ALLOCATE(TIT_VLIST(4)%PTR%STR(TIT_VLIST(4)%PTR%LENGTH_OF_STR))
        WRITE(TEMP, '(I4)') CASE_ID
        DO I = 1, TIT_VLIST(4)%PTR%LENGTH_OF_STR
            TIT_VLIST(4)%PTR%STR(I) = TEMP(I:I)
        END DO
        
        ! 5 FOR Ref Time
        J = 8
        ALLOCATE(TIT_VLIST(5)%PTR)
        TIT_VLIST(5)%PTR%LENGTH_OF_STR = J
        ALLOCATE(TIT_VLIST(5)%PTR%STR(TIT_VLIST(5)%PTR%LENGTH_OF_STR))
        WRITE(TEMP, '(F8.1)') REF_TIME
        DO I = 1, TIT_VLIST(5)%PTR%LENGTH_OF_STR
            TIT_VLIST(5)%PTR%STR(I) = TEMP(I:I)
        END DO  
        
        ! 6 FOR Ref BU
        J = 6
        ALLOCATE(TIT_VLIST(6)%PTR)
        TIT_VLIST(6)%PTR%LENGTH_OF_STR = J
        ALLOCATE(TIT_VLIST(6)%PTR%STR(TIT_VLIST(6)%PTR%LENGTH_OF_STR))
        WRITE(TEMP, '(I6)') REF_BU
        DO I = 1, TIT_VLIST(6)%PTR%LENGTH_OF_STR
            TIT_VLIST(6)%PTR%STR(I) = TEMP(I:I)
        END DO
                
        ! 7 FOR TITLE
        ALLOCATE(TIT_VLIST(7)%PTR)
        TIT_VLIST(7)%PTR%LENGTH_OF_STR = TITLE%LENGTH_OF_STR
        ALLOCATE(TIT_VLIST(7)%PTR%STR(TIT_VLIST(7)%PTR%LENGTH_OF_STR))
        DO I = 1, TITLE%LENGTH_OF_STR
            TIT_VLIST(7)%PTR%STR(I) = TITLE%STR(I)
        END DO      
        ! <- ############## PREPARE CASE TITLE ##############
        

        
        SELECT CASE (PRINT_OPTION)
        
        CASE (1)
        ! OUTPUT CROSS SECTION DATA FILE INFO

            CALL OUTPUT_CASE_CD_READ(PTR, TIT_VLIST)
        CASE (2)
            CALL OUTPUT_CASE_FUEL_COMP(PTR, TIT_VLIST)
        CASE (3)
            CALL OUPUT_CASE_FUEL_INSERT_SUM(PTR, TIT_VLIST)
        CASE DEFAULT
            ! NOTHING HERE NOW
        END SELECT
        
        CHA_MATR_LNK => PTR
        
        DEALLOCATE(TIT_VLIST)
    END SUBROUTINE OUTPUT_CASES
    
    ! CROSS SECTION DATA FILES READ
    SUBROUTINE OUTPUT_CASE_CD_READ(CHA_MATR_LNK, TIT_VLIST)
        IMPLICIT NONE
        TYPE(MATRIX_OF_CHA_NODE),   POINTER,     INTENT(IN OUT) :: CHA_MATR_LNK
        TYPE(POINTER_ARRAY_OF_STR), ALLOCATABLE, INTENT(IN OUT) :: TIT_VLIST(:)
        
        TYPE(MATRIX_OF_CHA),      POINTER :: LOGO_OUT => NULL()
        TYPE(MATRIX_OF_CHA),      POINTER :: TABLE_OUT => NULL()
        TYPE(MATRIX_OF_CHA_NODE), POINTER :: PTR => NULL()
        TYPE(TABLE) :: TABLE_DATA
        TYPE(COLUMN), TARGET, ALLOCATABLE :: TEMP_COLUMN_ARRAY(:)
        TYPE(COLUMN), POINTER :: TEMP_COLUMN => NULL()
        TYPE(DATA_VECTOR), POINTER :: TEMP_VEC => NULL()
        INTEGER(NM_INT), PARAMETER :: FIXED_COLUMNS = 5 ! 5
        INTEGER(NM_INT), PARAMETER :: LAST_TITLE_LINE = 2
        INTEGER(NM_INT), PARAMETER :: FIXED_SERIAL_WIDTH = 3
        INTEGER(NM_INT), PARAMETER :: FIXED_COLUMN_GAP_WIDTH = 1
        INTEGER(NM_INT), PARAMETER :: FIXED_ROW_BLANK = 1
        CHARACTER(LEN=*), PARAMETER :: SERIAL_NUM_FMT = '(I3)'
        CHARACTER(LEN=*), PARAMETER :: FILE_SIZE_FMT = '(I9)'
        TYPE(ARRAY_OF_STR),  TARGET, ALLOCATABLE :: SERIAL(:)
        TYPE(ARRAY_OF_STR), DIMENSION(1), TARGET :: COLUMN_TITEL_1, COLUMN_TITEL_3, COLUMN_TITEL_5
        TYPE(ARRAY_OF_STR), DIMENSION(2), TARGET :: COLUMN_TITEL_2, COLUMN_TITEL_4
        TYPE(DATA_VECTOR), TARGET :: VEC_1, VEC_2, VEC_3, VEC_4, VEC_5
        TYPE(ARRAY_OF_STR), POINTER :: AS_PTR => NULL()
        TYPE(ARRAY_OF_STR), POINTER :: TEMP_TITLE(:) => NULL()
        CHARACTER, POINTER :: TEMP_FMT(:) => NULL()
        CHARACTER, TARGET, ALLOCATABLE :: FMT_1(:)
        INTEGER(NM_INT) :: I, J
        INTEGER(NM_INT) :: TOTAL_ITEMS
        INTEGER(NM_INT) :: TOTAL_HEIGHT
        INTEGER(NM_INT) :: CONTENT_ROW_FROM
        INTEGER(NM_INT) :: TITLE_ROW_NUMBER
        INTEGER(NM_INT) :: COLUMN_FROM
        INTEGER(NM_INT) :: COLUMN_PRT_WIDTH
        INTEGER(NM_INT) :: FMT_LEN
        CHARACTER(LEN=100) :: TEMP     
         
        
        
        TOTAL_ITEMS = CASE_CD_READ_ITEM_NUM
        PTR => CHA_MATR_LNK
        
        CALL GENERATE_LOGO_TITLE(LOGO_OUT, TIT_VLIST)
        
        CALL APPEND_AFTER_MAT_CHA_LINK(PTR, LOGO_OUT)
        
        I = 3
        CALL INSERT_RETURN(I, PTR)
        CALL INSERT_STRING(CASE_CD_READ_STR_01, PTR)
        I = 1
        CALL INSERT_RETURN(I, PTR)
        
        ! GENERATE TABLE DATA
        TABLE_DATA%COLUMN_NUMBER = FIXED_COLUMNS
        ALLOCATE(TEMP_COLUMN_ARRAY(FIXED_COLUMNS))
        DO I = 1, FIXED_COLUMNS
            ALLOCATE(TEMP_COLUMN_ARRAY(I)%DATA_VEC)
        END DO
        TABLE_DATA%COLUMN_POINTER => TEMP_COLUMN_ARRAY
        
        TOTAL_HEIGHT = LAST_TITLE_LINE + TOTAL_ITEMS + FIXED_ROW_BLANK
        CONTENT_ROW_FROM = LAST_TITLE_LINE + FIXED_ROW_BLANK + 1
        ! COLUMN 1 FOR: No.
        !               ---
        ALLOCATE(SERIAL(TOTAL_ITEMS))
        DO I = 1, TOTAL_ITEMS
            ALLOCATE(SERIAL(I)%STR(FIXED_SERIAL_WIDTH))
            SERIAL(I)%LENGTH_OF_STR = FIXED_SERIAL_WIDTH
            WRITE(TEMP, SERIAL_NUM_FMT) I
            DO J = 1, 3
                SERIAL(I)%STR(J) = TEMP(J:J)
            END DO
        END DO
       !COLUMN_FILLING(COLUMN_PTR, DATA_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, &
	   !TITLE_ROW_TO, CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, FMT_LEN, FMT)
        TITLE_ROW_NUMBER = 1
        COLUMN_FROM = 1
        COLUMN_PRT_WIDTH = FIXED_SERIAL_WIDTH
        VEC_1%STR_PTR => SERIAL
        VEC_1%DATA_LENGTH = TOTAL_ITEMS
        AS_PTR => COLUMN_TITEL_1(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0019)  
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(1)
        TEMP_VEC => VEC_1
        TEMP_TITLE => COLUMN_TITEL_1
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE)
        
        ! COLUMN 2 FOR: File Size
        !                (Bytes)
        !               ---------
        TITLE_ROW_NUMBER = 2
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 9
        VEC_2%INT_PTR => CASE_CD_READ_01
        VEC_2%DATA_LENGTH = TOTAL_ITEMS
        AS_PTR => COLUMN_TITEL_2(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0020_1)
        AS_PTR => COLUMN_TITEL_2(2)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0020_2)   
        FMT_LEN = LEN(FILE_SIZE_FMT)
        ALLOCATE(FMT_1(FMT_LEN))
        DO J = 1, FMT_LEN
            FMT_1(J) = FILE_SIZE_FMT(J : J)
        END DO
        TEMP_FMT => FMT_1
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(2)
        TEMP_VEC => VEC_2
        TEMP_TITLE => COLUMN_TITEL_2
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)
    
        ! COLUMN 3 FOR:    Last Modified
        !               -------------------
        TITLE_ROW_NUMBER = 1
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 19
        VEC_3%STR_PTR => CASE_CD_READ_02
        VEC_3%DATA_LENGTH = TOTAL_ITEMS
        AS_PTR => COLUMN_TITEL_3(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0021) 
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(3)
        TEMP_VEC => VEC_3
        TEMP_TITLE => COLUMN_TITEL_3
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE)
         
        ! COLUMN 4 FOR: AUTOLINK
        !                 Ver.
        !               --------        
        TITLE_ROW_NUMBER = 2
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 8
        VEC_4%STR_PTR => CASE_CD_READ_03
        VEC_4%DATA_LENGTH = TOTAL_ITEMS
        AS_PTR => COLUMN_TITEL_4(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0022_1)
        AS_PTR => COLUMN_TITEL_4(2)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0022_2)
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(4)
        TEMP_VEC => VEC_4
        TEMP_TITLE => COLUMN_TITEL_4
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE)
             
        ! COLUMN 5 FOR:      File Name
        !               -------------------
        TITLE_ROW_NUMBER = 1
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        I = 0
        ! FIND MAX COLUMN WIDTH
        DO J = 1, TOTAL_ITEMS
            IF (I .LT. CASE_CD_READ_04(J)%LENGTH_OF_STR) THEN
                I = CASE_CD_READ_04(J)%LENGTH_OF_STR
            END IF
        END DO
        COLUMN_PRT_WIDTH = I
        VEC_5%STR_PTR => CASE_CD_READ_04
        VEC_5%DATA_LENGTH = TOTAL_ITEMS
        AS_PTR => COLUMN_TITEL_5(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0023)
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(5)
        TEMP_VEC => VEC_5
        TEMP_TITLE => COLUMN_TITEL_5
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE)        
        
        
        
        ! FIXED_ROW_BLANK FOR '----------'
        TABLE_DATA%TABLE_PRT_HEIGHT = LAST_TITLE_LINE + TOTAL_ITEMS + FIXED_ROW_BLANK
        TABLE_DATA%TABLE_PRT_WIDTH = 0
        DO I = 1, FIXED_COLUMNS
            TABLE_DATA%TABLE_PRT_WIDTH = TABLE_DATA%TABLE_PRT_WIDTH + TABLE_DATA%COLUMN_POINTER(I)%COLUMN_PRT_WIDTH &
            + TABLE_COLUMN_GAP_WIDTH
        END DO
        TABLE_DATA%TABLE_PRT_WIDTH = TABLE_DATA%TABLE_PRT_WIDTH - TABLE_COLUMN_GAP_WIDTH
        CALL TABLE_VIEW(TABLE_DATA, TABLE_OUT)
        CALL APPEND_AFTER_MAT_CHA_LINK(PTR, TABLE_OUT)
        
        CHA_MATR_LNK => PTR
        
        DEALLOCATE(TEMP_COLUMN_ARRAY)
        DEALLOCATE(SERIAL)
        DEALLOCATE(FMT_1)
    END SUBROUTINE OUTPUT_CASE_CD_READ
    
    ! FUEL COMPOSITION AND ORIENTATION
    SUBROUTINE OUTPUT_CASE_FUEL_COMP(CHA_MATR_LNK, TIT_VLIST)
        IMPLICIT NONE
        TYPE(MATRIX_OF_CHA_NODE),   POINTER,     INTENT(IN OUT) :: CHA_MATR_LNK
        TYPE(POINTER_ARRAY_OF_STR), ALLOCATABLE, INTENT(IN OUT) :: TIT_VLIST(:)
        
        TYPE(MATRIX_OF_CHA),      POINTER :: LOGO_OUT => NULL()
        TYPE(MATRIX_OF_CHA),      POINTER :: TABLE_OUT => NULL()
        TYPE(MATRIX_OF_CHA_NODE), POINTER :: PTR => NULL()
        TYPE(MATRIX_OF_CHA),      POINTER :: CORE_PRINT_FUEL_COMP => NULL()
        LOGICAL,                PARAMETER :: CORE_PRINT_MESH_ON = .TRUE.
        INTEGER(NM_INT)                  :: I, J
        PTR => CHA_MATR_LNK
        
        CALL GENERATE_LOGO_TITLE(LOGO_OUT, TIT_VLIST)
        
        CALL APPEND_AFTER_MAT_CHA_LINK(PTR, LOGO_OUT)
        
        I = 3
        CALL INSERT_RETURN(I, PTR)
        CALL INSERT_STRING(CASE_FUEL_COMP_STR_01, PTR)
        I = 1
        CALL INSERT_RETURN(I, PTR)

        CALL CORE_VIEW_RADIAL_ASSEMBLY(CASE_FUEL_COMP_01, CASE_FUEL_COMP_MAT_DIM, CORE_PRINT_FUEL_COMP, CORE_PRINT_MESH_ON)
        CALL APPEND_AFTER_MAT_CHA_LINK(PTR, CORE_PRINT_FUEL_COMP)
        
        CHA_MATR_LNK => PTR
    END SUBROUTINE OUTPUT_CASE_FUEL_COMP
    
    ! FULE AND INSERT PLACEMENT SUMMARY
    SUBROUTINE OUPUT_CASE_FUEL_INSERT_SUM(CHA_MATR_LNK, TIT_VLIST)
        IMPLICIT NONE
        TYPE(MATRIX_OF_CHA_NODE),   POINTER,     INTENT(IN OUT) :: CHA_MATR_LNK
        TYPE(POINTER_ARRAY_OF_STR), ALLOCATABLE, INTENT(IN OUT) :: TIT_VLIST(:)
        
        TYPE(MATRIX_OF_CHA),      POINTER :: LOGO_OUT => NULL()
        TYPE(MATRIX_OF_CHA_NODE), POINTER :: PTR => NULL()
        INTEGER(NM_INT) :: I
        
        PTR => CHA_MATR_LNK
        
        CALL GENERATE_LOGO_TITLE(LOGO_OUT, TIT_VLIST)
        
        CALL APPEND_AFTER_MAT_CHA_LINK(PTR, LOGO_OUT)
        
        I = 3
        CALL INSERT_RETURN(I, PTR)
        CALL INSERT_STRING(CASE_FUEL_INST_SUM_STR_01, PTR)
        I = 1
        CALL INSERT_RETURN(I, PTR)
        
        CALL FUEL_INSERT_SUM_FA(PTR)
        
        CHA_MATR_LNK => PTR
    END SUBROUTINE OUPUT_CASE_FUEL_INSERT_SUM
    
    ! FOR FUEL ASSEMBLY PLACEMENT 
    SUBROUTINE FUEL_INSERT_SUM_FA(CHA_MATR_LNK)
        IMPLICIT NONE
        TYPE(MATRIX_OF_CHA_NODE),   POINTER,     INTENT(IN OUT) :: CHA_MATR_LNK
        
        TYPE(MATRIX_OF_CHA_NODE), POINTER :: PTR => NULL()
        INTEGER(NM_INT), PARAMETER :: FIXED_COLUMNS = 11 !12
        INTEGER(NM_INT), PARAMETER :: LAST_TITLE_LINE = 3
        INTEGER(NM_INT), PARAMETER :: LAST_TITLE_LINE_S_1 = 1
        INTEGER(NM_INT), PARAMETER :: FIXED_ROW_BLANK = 1
        INTEGER(NM_INT)            :: FMT_LEN = 1
        TYPE(TABLE) :: TABLE_DATA
        TYPE(COLUMN), TARGET, ALLOCATABLE :: TEMP_COLUMN_ARRAY(:)
        TYPE(COLUMN), TARGET, ALLOCATABLE :: TEMP_COLUMN_ARRAY_1(:)
        TYPE(COLUMN), TARGET, ALLOCATABLE :: TEMP_COLUMN_ARRAY_2(:)
        TYPE(COLUMN), POINTER :: TEMP_COLUMN => NULL()
        TYPE(COLUMN), POINTER :: TEMP_SUB_COLUMN(:) => NULL()
        TYPE(DATA_VECTOR), POINTER :: TEMP_VEC => NULL()
        TYPE(ARRAY_OF_STR), POINTER :: TEMP_TITLE(:) => NULL()
        CHARACTER, POINTER :: TEMP_FMT(:) => NULL()
        TYPE(DATA_VECTOR), TARGET ::  VEC_1,  VEC_2,  VEC_3,  VEC_4, VEC_5, VEC_6, VEC_7, VEC_8, VEC_9, VEC_10, &
                                     VEC_11, VEC_12, VEC_13, VEC_14 
        CHARACTER,    TARGET, ALLOCATABLE :: FMT_1(:)
        CHARACTER,    TARGET, ALLOCATABLE :: FMT_2(:)
        CHARACTER,    TARGET, ALLOCATABLE :: FMT_3(:)
        CHARACTER,    TARGET, ALLOCATABLE :: FMT_4(:)
        CHARACTER,    TARGET, ALLOCATABLE :: FMT_5(:) 
        CHARACTER,    TARGET, ALLOCATABLE :: FMT_6(:) 
        CHARACTER,    TARGET, ALLOCATABLE :: FMT_7(:)
        TYPE(MATRIX_OF_CHA),      POINTER :: TABLE_OUT => NULL()
        TYPE(ARRAY_OF_STR), DIMENSION(1), TARGET :: COLUMN_TITEL_1,   &
                                                    COLUMN_TITEL_2,   &
                                                    COLUMN_TITEL_2_1, &
                                                    COLUMN_TITEL_2_2, &
                                                    COLUMN_TITEL_3,   &
                                                    COLUMN_TITEL_3_1, &
                                                    COLUMN_TITEL_3_2, &
                                                    COLUMN_TITEL_3_3, &
                                                    COLUMN_TITEL_4
        TYPE(ARRAY_OF_STR), DIMENSION(3), TARGET :: COLUMN_TITEL_5,   &
                                                    COLUMN_TITEL_6,   &
                                                    COLUMN_TITEL_7 
        TYPE(ARRAY_OF_STR), DIMENSION(2), TARGET :: COLUMN_TITEL_8,   &
                                                    COLUMN_TITEL_9,   &
                                                    COLUMN_TITEL_10,  &
                                                    COLUMN_TITEL_11
        INTEGER(NM_INT) :: I, J
        TYPE(ARRAY_OF_STR), POINTER :: AS_PTR => NULL()
        INTEGER(NM_INT) :: TOTAL_HEIGHT
        INTEGER(NM_INT) :: CONTENT_ROW_FROM
        INTEGER(NM_INT) :: TITLE_ROW_NUMBER
        INTEGER(NM_INT) :: COLUMN_FROM
        INTEGER(NM_INT) :: COLUMN_PRT_WIDTH
        INTEGER(NM_INT) :: SUB_COLUMN_NUMBER
        CHARACTER(LEN=*), PARAMETER :: BURNUP_FMT = '(F9.1)'
		CHARACTER(LEN=*), PARAMETER :: IFBA_N_FMT = '(I4)'
		CHARACTER(LEN=*), PARAMETER :: FRAC_FMT = '(F5.2)'
		CHARACTER(LEN=*), PARAMETER :: GAD_N_FMT = '(I3)'
        PTR => CHA_MATR_LNK
        
        
        I = 1
        CALL INSERT_RETURN(I, PTR)
        CALL INSERT_STRING(CASE_FUEL_INST_SUM_STR_02, PTR)
        I = 1
        CALL INSERT_RETURN(I, PTR)
        
        ! GENERATE TABLE DATA
        TABLE_DATA%COLUMN_NUMBER = FIXED_COLUMNS
        ALLOCATE(TEMP_COLUMN_ARRAY(FIXED_COLUMNS))
        !DO I = 1, FIXED_COLUMNS
        !    ALLOCATE(TEMP_COLUMN_ARRAY(I)%DATA_VEC)
        !END DO
        TABLE_DATA%COLUMN_POINTER => TEMP_COLUMN_ARRAY      
        
        TOTAL_HEIGHT = LAST_TITLE_LINE + CASE_FUEL_INST_FA_ITEM_NUM + FIXED_ROW_BLANK
        CONTENT_ROW_FROM = LAST_TITLE_LINE + FIXED_ROW_BLANK + 1        
        ! COLUMN 1 FOR:   Loc.
        !                 ----
        !COLUMN_FILLING(COLUMN_PTR, DATA_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, &
	    !TITLE_ROW_TO, CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, FMT_LEN, FMT)
        TITLE_ROW_NUMBER = 1
        COLUMN_FROM = 1
        COLUMN_PRT_WIDTH = 4
        VEC_1%STR_PTR => CASE_FUEL_INST_FA_01
        VEC_1%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_1(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0024)
        FMT_LEN = 1
        ALLOCATE(FMT_1(FMT_LEN))
        FMT_1(1) = 'L'
        TEMP_FMT => FMT_1
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(1)
        TEMP_VEC => VEC_1
        TEMP_TITLE => COLUMN_TITEL_1
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)
        
        ! COLUMN 2 FOR :        Assembly     
        !                  ------------------
        !                     ID       TYPE  
        !                  --------  --------
		!COLUMN_WITH_SUBCOLUMN_FILLING(COLUMN_PTR, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, TITLE_ROW_TO, &
		!CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, SUB_COLUMN_NUMBER, SUBCOLUMN_PTR)       
        TITLE_ROW_NUMBER = 1
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 18
        SUB_COLUMN_NUMBER = 2
        AS_PTR => COLUMN_TITEL_2(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0025)
        ALLOCATE(TEMP_COLUMN_ARRAY_1(SUB_COLUMN_NUMBER))
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(2)
        TEMP_TITLE => COLUMN_TITEL_2
        TEMP_SUB_COLUMN => TEMP_COLUMN_ARRAY_1
        CALL COLUMN_FILLING(TEMP_COLUMN, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE_S_1, &
			CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, SUB_COLUMN_NUMBER, TEMP_SUB_COLUMN)
        ! COLUMN 2_1 FOR:    ID   
        !                 --------
        !COLUMN_FILLING(COLUMN_PTR, DATA_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, &
	    !TITLE_ROW_TO, CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, FMT_LEN, FMT)
        TITLE_ROW_NUMBER = 1
        COLUMN_FROM = COLUMN_FROM
        COLUMN_PRT_WIDTH = 8
        VEC_2%STR_PTR => CASE_FUEL_INST_FA_02
        VEC_2%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_2_1(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0025_1)
        FMT_LEN = 1
        ALLOCATE(FMT_2(FMT_LEN))
        FMT_2(1) = 'M'
        TEMP_FMT => FMT_2
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(2)%SUB_COLUMN_POINTER(1)
        TEMP_VEC => VEC_2
        TEMP_TITLE => COLUMN_TITEL_2_1
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)        
        ! COLUMN 2-2 FOR:   TYPE   
        !                 --------
        TITLE_ROW_NUMBER = 1
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 8
        VEC_3%STR_PTR => CASE_FUEL_INST_FA_03
        VEC_3%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_2_2(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0025_2)
        FMT_LEN = 1
        ALLOCATE(FMT_3(FMT_LEN))
        FMT_3(1) = 'R'
        TEMP_FMT => FMT_3
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(2)%SUB_COLUMN_POINTER(2)
        TEMP_VEC => VEC_3
        TEMP_TITLE => COLUMN_TITEL_2_2
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT) 
        
        ! COLUMN 3 FOR :       Previous Loc.     
        !                  ---------------------
        !                   I-J   PlantID  Cycle
        !                  -----  -------  -----
		!COLUMN_WITH_SUBCOLUMN_FILLING(COLUMN_PTR, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, TITLE_ROW_TO, &
		!CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, SUB_COLUMN_NUMBER, SUBCOLUMN_PTR)       
        TITLE_ROW_NUMBER = 1
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 21
        SUB_COLUMN_NUMBER = 3
        AS_PTR => COLUMN_TITEL_3(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0026)
        ALLOCATE(TEMP_COLUMN_ARRAY_2(SUB_COLUMN_NUMBER))
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(3)
        TEMP_TITLE => COLUMN_TITEL_3
        TEMP_SUB_COLUMN => TEMP_COLUMN_ARRAY_2
        CALL COLUMN_FILLING(TEMP_COLUMN, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE_S_1, &
			CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, SUB_COLUMN_NUMBER, TEMP_SUB_COLUMN)
        ! COLUMN 3_1 FOR:  I-J   
        !                 -----    
        !COLUMN_FILLING(COLUMN_PTR, DATA_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, &
	    !TITLE_ROW_TO, CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, FMT_LEN, FMT)
        TITLE_ROW_NUMBER = 1
        COLUMN_FROM = COLUMN_FROM
        COLUMN_PRT_WIDTH = 5
        VEC_4%STR_PTR => CASE_FUEL_INST_FA_04
        VEC_4%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_3_1(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0026_1)
        FMT_LEN = 1
        TEMP_FMT => FMT_3
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(3)%SUB_COLUMN_POINTER(1)
        TEMP_VEC => VEC_4
        TEMP_TITLE => COLUMN_TITEL_3_1
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)        
        ! COLUMN 3-2 FOR: PlantID 
        !                 -------
        TITLE_ROW_NUMBER = 1
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 7
        VEC_5%STR_PTR => CASE_FUEL_INST_FA_05
        VEC_5%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_3_2(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0026_2)
        FMT_LEN = 1
        TEMP_FMT => FMT_3
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(3)%SUB_COLUMN_POINTER(2)
        TEMP_VEC => VEC_5
        TEMP_TITLE => COLUMN_TITEL_3_2
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)         
        ! COLUMN 3-3 FOR: Cycle 
        !                 -----
        TITLE_ROW_NUMBER = 1
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 5
        VEC_6%STR_PTR => CASE_FUEL_INST_FA_06
        VEC_6%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_3_3(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0026_3)
        FMT_LEN = 1
        TEMP_FMT => FMT_3
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(3)%SUB_COLUMN_POINTER(3)
        TEMP_VEC => VEC_6
        TEMP_TITLE => COLUMN_TITEL_3_3
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)            

        ! COLUMN 4 FOR:  Shuffle 
        !                -------
        !COLUMN_FILLING(COLUMN_PTR, DATA_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, &
	    !TITLE_ROW_TO, CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, FMT_LEN, FMT)
        TITLE_ROW_NUMBER = 1
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 7
        VEC_7%STR_PTR => CASE_FUEL_INST_FA_07
        VEC_7%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_4(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0027)
        FMT_LEN = 1
        TEMP_FMT => FMT_3
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(4)
        TEMP_VEC => VEC_7
        TEMP_TITLE => COLUMN_TITEL_4
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)

        ! COLUMN 5 FOR:  Average
        !                 Burnup
        !                (MWD/MTM) 
        !                ---------
        !COLUMN_FILLING(COLUMN_PTR, DATA_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, &
	    !TITLE_ROW_TO, CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, FMT_LEN, FMT)
        TITLE_ROW_NUMBER = 3
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 9
        VEC_8%REL_PTR => CASE_FUEL_INST_FA_08
        VEC_8%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_5(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0028_1)
        AS_PTR => COLUMN_TITEL_5(2)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0028_2)
        AS_PTR => COLUMN_TITEL_5(3)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0028_3)
        FMT_LEN = LEN(BURNUP_FMT)
        ALLOCATE(FMT_4(FMT_LEN))
        DO J = 1, FMT_LEN
            FMT_4(J) = BURNUP_FMT(J : J)
        END DO
        TEMP_FMT => FMT_4
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(5)
        TEMP_VEC => VEC_8
        TEMP_TITLE => COLUMN_TITEL_5
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)

        ! COLUMN 6 FOR:   Maximum
        !                 Rod BU
        !                (MWD/MTM) 
        !                ---------
        !COLUMN_FILLING(COLUMN_PTR, DATA_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, &
	    !TITLE_ROW_TO, CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, FMT_LEN, FMT)
        TITLE_ROW_NUMBER = 3
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 9
        VEC_9%REL_PTR => CASE_FUEL_INST_FA_09
        VEC_9%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_6(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0029_1)
        AS_PTR => COLUMN_TITEL_6(2)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0029_2)
        AS_PTR => COLUMN_TITEL_6(3)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0028_3)
        TEMP_FMT => FMT_4
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(6)
        TEMP_VEC => VEC_9
        TEMP_TITLE => COLUMN_TITEL_6
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)

        ! COLUMN 7 FOR:  Residence
        !                  Time   
        !                 (Days) 
        !                ---------
        !COLUMN_FILLING(COLUMN_PTR, DATA_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, &
	    !TITLE_ROW_TO, CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, FMT_LEN, FMT)
        TITLE_ROW_NUMBER = 3
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 9
        VEC_10%REL_PTR => CASE_FUEL_INST_FA_10
        VEC_10%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_7(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0030_1)
        AS_PTR => COLUMN_TITEL_7(2)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0030_2)
        AS_PTR => COLUMN_TITEL_7(3)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0030_3)
        TEMP_FMT => FMT_4
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(7)
        TEMP_VEC => VEC_10
        TEMP_TITLE => COLUMN_TITEL_7
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)
        	
        ! COLUMN 8 FOR:  No.
        !                IFBA
        !                ----
        !COLUMN_FILLING(COLUMN_PTR, DATA_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, &
	    !TITLE_ROW_TO, CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, FMT_LEN, FMT)
        TITLE_ROW_NUMBER = 2
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 4
        VEC_11%INT_PTR => CASE_FUEL_INST_FA_11
        VEC_11%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_8(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0019)
        AS_PTR => COLUMN_TITEL_8(2)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0031_2)
        FMT_LEN = LEN(IFBA_N_FMT)
        ALLOCATE(FMT_5(FMT_LEN))
        DO J = 1, FMT_LEN
            FMT_5(J) = IFBA_N_FMT(J : J)
        END DO      
        TEMP_FMT => FMT_5
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(8)
        TEMP_VEC => VEC_11
        TEMP_TITLE => COLUMN_TITEL_8
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)

        ! COLUMN 9 FOR:  IFBA
        !                Frac.
        !                -----
        !COLUMN_FILLING(COLUMN_PTR, DATA_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, &
	    !TITLE_ROW_TO, CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, FMT_LEN, FMT)
        TITLE_ROW_NUMBER = 2
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 5
        VEC_12%REL_PTR => CASE_FUEL_INST_FA_12
        VEC_12%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_9(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0031_2)
        AS_PTR => COLUMN_TITEL_9(2)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0032_2)
        FMT_LEN = LEN(FRAC_FMT)
        ALLOCATE(FMT_6(FMT_LEN))
        DO J = 1, FMT_LEN
            FMT_6(J) = FRAC_FMT(J : J)
        END DO      
        TEMP_FMT => FMT_6
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(9)
        TEMP_VEC => VEC_12
        TEMP_TITLE => COLUMN_TITEL_9
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)
        	
        ! COLUMN 10 FOR:  No.
        !                 Gad
        !                 ---
        !COLUMN_FILLING(COLUMN_PTR, DATA_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, &
	    !TITLE_ROW_TO, CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, FMT_LEN, FMT)
        TITLE_ROW_NUMBER = 2
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 3
        VEC_13%INT_PTR => CASE_FUEL_INST_FA_13
        VEC_13%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_10(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0019)
        AS_PTR => COLUMN_TITEL_10(2)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0033_2)
        FMT_LEN = LEN(GAD_N_FMT)
        ALLOCATE(FMT_7(FMT_LEN))
        DO J = 1, FMT_LEN
            FMT_7(J) = GAD_N_FMT(J : J)
        END DO      
        TEMP_FMT => FMT_7
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(10)
        TEMP_VEC => VEC_13
        TEMP_TITLE => COLUMN_TITEL_10
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)
        	
        ! COLUMN 11 FOR:  No.
        !                 Erb
        !                 ---
        !COLUMN_FILLING(COLUMN_PTR, DATA_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, &
	    !TITLE_ROW_TO, CONTENT_ROW_FROM, COLUMN_FROM, TITLE_POINTER, FMT_LEN, FMT)
        TITLE_ROW_NUMBER = 2
        COLUMN_FROM = COLUMN_FROM + COLUMN_PRT_WIDTH + TABLE_COLUMN_GAP_WIDTH
        COLUMN_PRT_WIDTH = 3
        VEC_14%INT_PTR => CASE_FUEL_INST_FA_14
        VEC_14%DATA_LENGTH = CASE_FUEL_INST_FA_ITEM_NUM
        AS_PTR => COLUMN_TITEL_11(1)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0019)
        AS_PTR => COLUMN_TITEL_11(2)
        CALL CPY_ARY_OF_STR(AS_PTR, LABLE_0034_2)
        FMT_LEN = LEN(GAD_N_FMT)
        TEMP_FMT => FMT_7
        TEMP_COLUMN => TABLE_DATA%COLUMN_POINTER(11)
        TEMP_VEC => VEC_14
        TEMP_TITLE => COLUMN_TITEL_11
        CALL COLUMN_FILLING(TEMP_COLUMN, TEMP_VEC, COLUMN_PRT_WIDTH, TOTAL_HEIGHT, TITLE_ROW_NUMBER, LAST_TITLE_LINE, &
        	CONTENT_ROW_FROM, COLUMN_FROM, TEMP_TITLE, FMT_LEN, TEMP_FMT)
          
        ! FIXED_ROW_BLANK FOR '----------'
        TABLE_DATA%TABLE_PRT_HEIGHT = TABLE_DATA%COLUMN_POINTER(1)%TOTAL_HEIGHT
        TABLE_DATA%TABLE_PRT_WIDTH = 0
        DO I = 1, FIXED_COLUMNS
            TABLE_DATA%TABLE_PRT_WIDTH = TABLE_DATA%TABLE_PRT_WIDTH + TABLE_DATA%COLUMN_POINTER(I)%COLUMN_PRT_WIDTH &
            + TABLE_COLUMN_GAP_WIDTH
        END DO
        TABLE_DATA%TABLE_PRT_WIDTH = TABLE_DATA%TABLE_PRT_WIDTH - TABLE_COLUMN_GAP_WIDTH
        
        CALL TABLE_VIEW(TABLE_DATA, TABLE_OUT)
        CALL APPEND_AFTER_MAT_CHA_LINK(PTR, TABLE_OUT)
        
        CHA_MATR_LNK => PTR
        
    END SUBROUTINE FUEL_INSERT_SUM_FA
    
    ! MORE FUNCTIONS WILL BE BUILT HERE
    

END MODULE CYCAS_OUTPUT_COMPONENT