MODULE IO_FUNCTION
USE BASIC_DATA
IMPLICIT NONE

CONTAINS
	FUNCTION SAFE_FILEID()
		IMPLICIT NONE
		INTEGER :: SAFE_FILEID
		INTEGER, PARAMETER :: MIN = 1
		INTEGER, PARAMETER :: MAX = 999
		INTEGER :: I = 1
		LOGICAL :: IS_OPENED
		
		DO I = MIN, MAX
			INQUIRE(UNIT=I, OPENED=IS_OPENED)
			IF (.NOT. IS_OPENED) THEN
				EXIT
			END IF
		END DO 
		
		SAFE_FILEID = I
		
		RETURN
	END FUNCTION SAFE_FILEID

END MODULE IO_FUNCTION