PROGRAM MAIN
USE BASIC_DATA
USE OUTPUT_PARAMETERS
USE DRAW
USE IO_FUNCTION
USE CYCAS_OUTPUT_COMPONENT
IMPLICIT NONE

INTEGER(NM_INT) :: I, J, K, L
TYPE(MATRIX_OF_CHA) :: TEMPLATE
TYPE(STR_MATRIX), ALLOCATABLE :: FUEL(:)
TYPE(STR_MATRIX), ALLOCATABLE :: CROD(:)
TYPE(STR_MATRIX), ALLOCATABLE :: CRODGP(:)
INTEGER(NM_INT) :: ARRMAC_LENGTH
TYPE(ARRAY_OF_STR) :: ASTR
TYPE(POINTER_ARRAY_OF_STR), ALLOCATABLE :: NAME_LIST(:)
TYPE(POINTER_ARRAY_OF_STR), ALLOCATABLE :: VALUE_LIST(:)
INTEGER(NM_INT) :: LIST_LENGTH
INTEGER :: FILEID
INTEGER(NM_INT) :: BLANK
CHARACTER :: BOUND_H
CHARACTER :: BOUND_V
CHARACTER :: CORNER
TYPE(MATRIX_OF_CHA_NODE), POINTER :: TXT_LNK_HEAD
TYPE(MATRIX_OF_CHA_NODE), POINTER :: PTR
TYPE(ARRAY_OF_STR)  :: STR_LABLE
TYPE(MATRIX_OF_CHA) :: LABLE_OUT
INTEGER :: CASE_ID
INTEGER :: JOB_ID
INTEGER :: REF_BU
REAL(DP) :: REF_TIME
TYPE(ARRAY_OF_STR) :: TITLE
INTEGER(NM_INT),    TARGET, ALLOCATABLE :: CA_CD_01(:)
TYPE(ARRAY_OF_STR), TARGET, ALLOCATABLE :: CA_CD_02(:)
TYPE(ARRAY_OF_STR), TARGET, ALLOCATABLE :: CA_CD_03(:)
TYPE(ARRAY_OF_STR), TARGET, ALLOCATABLE :: CA_CD_04(:)
TYPE(ARRAY_OF_STR), TARGET, ALLOCATABLE :: CA_FA_01(:)
TYPE(ARRAY_OF_STR), TARGET, ALLOCATABLE :: CA_FA_02(:)
TYPE(ARRAY_OF_STR), TARGET, ALLOCATABLE :: CA_FA_03(:)
TYPE(ARRAY_OF_STR), TARGET, ALLOCATABLE :: CA_FA_04(:)
TYPE(ARRAY_OF_STR), TARGET, ALLOCATABLE :: CA_FA_05(:)
TYPE(ARRAY_OF_STR), TARGET, ALLOCATABLE :: CA_FA_06(:)
TYPE(ARRAY_OF_STR), TARGET, ALLOCATABLE :: CA_FA_07(:)
REAL(DP),           TARGET, ALLOCATABLE :: CA_FA_08(:)
REAL(DP),           TARGET, ALLOCATABLE :: CA_FA_10(:)
INTEGER(NM_INT) ,   TARGET, ALLOCATABLE :: CA_FA_11(:)
REAL(DP),           TARGET, ALLOCATABLE :: CA_FA_12(:)
INTEGER(NM_INT) ,   TARGET, ALLOCATABLE :: CA_FA_13(:)

INTEGER(NM_INT) :: CA_OPT
CHARACTER(LEN=*), PARAMETER :: DAT_TIM = '2017/02/09 19:47:51'
CHARACTER(LEN=*), PARAMETER :: ALK_VER = '9.10.7'
CHARACTER(LEN=*), PARAMETER :: FIL_NAM = '/usr2/hany/test_ANC/cd file/CD_File/C0000000.h5'

CHARACTER(LEN=*),   PARAMETER :: FU_COMP_DEMO = 'D112068'
CHARACTER(LEN=*),   PARAMETER :: FU_ORIT = 'TRAN'
CHARACTER(LEN=*),   PARAMETER :: FA_NAME = 'A-9'
CHARACTER(LEN=*),   PARAMETER :: FA_ID = 'A03'
CHARACTER(LEN=*),   PARAMETER :: FA_TYPE = 'A1__000'
CHARACTER(LEN=*),   PARAMETER :: FA_I_J = 'Feed'
CHARACTER(LEN=*),   PARAMETER :: FA_PID = '-----'
CHARACTER(LEN=*),   PARAMETER :: FA_CYC = '-----'
CHARACTER(LEN=*),   PARAMETER :: FA_SHL = '----'
REAL(DP),           PARAMETER :: FA_BUR = 15000.0
INTEGER(NM_INT),   PARAMETER :: FU_COMP_DIS_DIM = 2

TYPE(STR_MATRIX), TARGET, ALLOCATABLE :: FU_COMP(:)




! TIME AND DATE

integer date_time(8)
character*10 b(3)
call date_and_time(b(1), b(2), b(3), date_time)

WRITE(*, *) date_time(1)
WRITE(*, *) date_time(2)
WRITE(*, *) date_time(3)
WRITE(*, *) date_time(4)
WRITE(*, *) date_time(5)
WRITE(*, *) date_time(6)
WRITE(*, *) date_time(7)
WRITE(*, *) date_time(8)
WRITE(*, *) b(1)
WRITE(*, *) b(2)
WRITE(*, *) b(3)

NULLIFY(TXT_LNK_HEAD, PTR)





CORE_DIMENSION = 15
ALLOCATE(CORE_LAYOUT(CORE_DIMENSION, CORE_DIMENSION))
CORE_LAYOUT = RESHAPE((/ 0,0,0,0,0,0,1,1,1,0,0,0,0,0,0, &
                         0,0,0,0,1,1,1,1,1,1,1,0,0,0,0, &
                         0,0,0,1,1,1,1,1,1,1,1,1,0,0,0, &
                         0,0,1,1,1,1,1,1,1,1,1,1,1,0,0, &
                         0,1,1,1,1,1,1,1,1,1,1,1,1,1,0, &
                         0,1,1,1,1,1,1,1,1,1,1,1,1,1,0, &
                         1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, &
                         1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, &
                         1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, &
                         0,1,1,1,1,1,1,1,1,1,1,1,1,1,0, &
                         0,1,1,1,1,1,1,1,1,1,1,1,1,1,0, &
                         0,0,1,1,1,1,1,1,1,1,1,1,1,0,0, &
                         0,0,0,1,1,1,1,1,1,1,1,1,0,0,0, &
                         0,0,0,0,1,1,1,1,1,1,1,0,0,0,0, &
                         0,0,0,0,0,0,1,1,1,0,0,0,0,0,0/), &
                         (/CORE_DIMENSION, CORE_DIMENSION/))
                         
ARRMAC_LENGTH = 1               
ALLOCATE(FUEL(ARRMAC_LENGTH))
ALLOCATE(CROD(ARRMAC_LENGTH))
ALLOCATE(CRODGP(ARRMAC_LENGTH))

! FILL ASSEMBLY LAYOUT
FUEL(1)%ROW_DIMENSION = CORE_DIMENSION
FUEL(1)%COLUMN_DIMENSION = CORE_DIMENSION
ALLOCATE(FUEL(1)%MATRIX(FUEL(1)%COLUMN_DIMENSION, FUEL(1)%ROW_DIMENSION))
DO I = 1, CORE_DIMENSION
	DO J = 1, CORE_DIMENSION
		IF (CORE_LAYOUT(J, I) .EQ. 1) THEN 
			FUEL(1)%MATRIX(J, I)%LENGTH_OF_STR = 7
			ALLOCATE(FUEL(1)%MATRIX(J, I)%STR(FUEL(1)%MATRIX(J, I)%LENGTH_OF_STR))
			FUEL(1)%MATRIX(J, I)%STR = (/'A', '1', '_','_','0','0','0'/)
		ELSE
			FUEL(1)%MATRIX(J, I)%LENGTH_OF_STR = 0
		END IF
		
	END DO
END DO
! FILL CONTROL ROD LAYOUT
CROD(1)%ROW_DIMENSION = CORE_DIMENSION
CROD(1)%COLUMN_DIMENSION = CORE_DIMENSION
ALLOCATE(CROD(1)%MATRIX(FUEL(1)%COLUMN_DIMENSION, FUEL(1)%ROW_DIMENSION))
DO I = 1, CORE_DIMENSION
	DO J = 1, CORE_DIMENSION
		IF (CORE_LAYOUT(J, I) .EQ. 1) THEN 
			CROD(1)%MATRIX(J, I)%LENGTH_OF_STR = 6
			ALLOCATE(CROD(1)%MATRIX(J, I)%STR(CROD(1)%MATRIX(J, I)%LENGTH_OF_STR))
			CROD(1)%MATRIX(J, I)%STR = (/' ', 'G', 'R', 'A', 'Y', ' '/)
		ELSE
			CROD(1)%MATRIX(J, I)%LENGTH_OF_STR = 0
		END IF
		
	END DO
END DO
! FILL CONTROL ROD GROUP LAYOUT
CRODGP(1)%ROW_DIMENSION = CORE_DIMENSION
CRODGP(1)%COLUMN_DIMENSION = CORE_DIMENSION
ALLOCATE(CRODGP(1)%MATRIX(FUEL(1)%COLUMN_DIMENSION, FUEL(1)%ROW_DIMENSION))
DO I = 1, CORE_DIMENSION
	DO J = 1, CORE_DIMENSION
		IF (CORE_LAYOUT(J, I) .EQ. 1) THEN 
			CRODGP(1)%MATRIX(J, I)%LENGTH_OF_STR = 4
			ALLOCATE(CRODGP(1)%MATRIX(J, I)%STR(CRODGP(1)%MATRIX(J, I)%LENGTH_OF_STR))
			CRODGP(1)%MATRIX(J, I)%STR = (/' ', 'M', 'A', ' '/)
		ELSE
			CRODGP(1)%MATRIX(J, I)%LENGTH_OF_STR = 0
		END IF
		
	END DO
END DO


ALLOCATE(FU_COMP(FU_COMP_DIS_DIM))
DO K = 1, FU_COMP_DIS_DIM
	FU_COMP(K)%ROW_DIMENSION = CORE_DIMENSION
	FU_COMP(K)%COLUMN_DIMENSION = CORE_DIMENSION
	ALLOCATE(FU_COMP(K)%MATRIX(CORE_DIMENSION, CORE_DIMENSION))
	DO I = 1, CORE_DIMENSION
		DO J = 1, CORE_DIMENSION
			IF (CORE_LAYOUT(J, I) .EQ. 1) THEN
				IF (K .EQ. 1) THEN
					FU_COMP(K)%MATRIX(J, I)%LENGTH_OF_STR = LEN(FU_COMP_DEMO)
					ALLOCATE(FU_COMP(K)%MATRIX(J, I)%STR(FU_COMP(K)%MATRIX(J, I)%LENGTH_OF_STR))
					DO L = 1, LEN(FU_COMP_DEMO)
						FU_COMP(K)%MATRIX(J, I)%STR(L) = FU_COMP_DEMO(L : L)
					END DO
				ELSE
					FU_COMP(K)%MATRIX(J, I)%LENGTH_OF_STR = LEN(FU_ORIT)
					ALLOCATE(FU_COMP(K)%MATRIX(J, I)%STR(FU_COMP(K)%MATRIX(J, I)%LENGTH_OF_STR))
					DO L = 1, LEN(FU_ORIT)
						FU_COMP(K)%MATRIX(J, I)%STR(L) = FU_ORIT(L : L)
					END DO
				END IF
			ELSE
				FU_COMP(K)%MATRIX(J, I)%LENGTH_OF_STR = 0
			END IF
		
		END DO
	END DO
END DO

CASE_FUEL_COMP_MAT_DIM = FU_COMP_DIS_DIM

CASE_FUEL_COMP_01 => FU_COMP


FILEID = SAFE_FILEID()
OPEN(NEWUNIT=FILEID, FILE='TEST_TEMPLATE.TXT')

CALL INITIAL_PARAMETERS()

LIST_LENGTH = 3
ALLOCATE(NAME_LIST(LIST_LENGTH))
ALLOCATE(VALUE_LIST(LIST_LENGTH))
DO I = 1, LIST_LENGTH
	ALLOCATE(NAME_LIST(I)%PTR)
	ALLOCATE(VALUE_LIST(I)%PTR)
END DO
CALL CPY_ARY_OF_STR(NAME_LIST(1)%PTR, PARANAME_0001)
CALL CPY_ARY_OF_STR(NAME_LIST(2)%PTR, PARANAME_0002)
CALL CPY_ARY_OF_STR(NAME_LIST(3)%PTR, PARANAME_0003)

CALL CPY_ARY_OF_STR(VALUE_LIST(1)%PTR, STDVALUE_0001)
CALL CPY_ARY_OF_STR(VALUE_LIST(2)%PTR, STDVALUE_0002)
CALL CPY_ARY_OF_STR(VALUE_LIST(3)%PTR, STDVALUE_0003)

CALL INITIAL_OUTPUT(TXT_LNK_HEAD)

PTR => TXT_LNK_HEAD
CALL OUTPUT_COREMAPS(FUEL, CROD, CRODGP, PTR, NAME_LIST, VALUE_LIST, LIST_LENGTH)

I = 3
CALL INSERT_RETURN(I, PTR)
CASE_ID = 1
JOB_ID = 8848
REF_TIME = 0.0
REF_BU = 0
TITLE%LENGTH_OF_STR = 8
ALLOCATE(TITLE%STR(TITLE%LENGTH_OF_STR))
TITLE%STR = ' '
TITLE%STR(1) = 'F'
TITLE%STR(2) = 'O'
TITLE%STR(3) = 'R'
TITLE%STR(4) = ' '
TITLE%STR(5) = 'T'
TITLE%STR(6) = 'E'
TITLE%STR(7) = 'S'
TITLE%STR(8) = 'T'



CASE_CD_READ_ITEM_NUM = 10
IF (ALLOCATED(CA_CD_01)) THEN
	DEALLOCATE(CA_CD_01)
END IF
ALLOCATE(CA_CD_01(CASE_CD_READ_ITEM_NUM))
CA_CD_01 = 1234567
CASE_CD_READ_01 => CA_CD_01

IF (ALLOCATED(CA_CD_02)) THEN
	DEALLOCATE(CA_CD_02)
END IF
ALLOCATE(CA_CD_02(CASE_CD_READ_ITEM_NUM))
K = LEN(DAT_TIM)
DO I = 1, CASE_CD_READ_ITEM_NUM
	CA_CD_02(I)%LENGTH_OF_STR = K
	ALLOCATE(CA_CD_02(I)%STR(K))
	DO J = 1, K
		CA_CD_02(I)%STR(J) = DAT_TIM(J : J)
	END DO
END DO
CASE_CD_READ_02 => CA_CD_02

IF (ALLOCATED(CA_CD_03)) THEN
	DEALLOCATE(CA_CD_03)
END IF
ALLOCATE(CA_CD_03(CASE_CD_READ_ITEM_NUM))
K = LEN(ALK_VER)
DO I = 1, CASE_CD_READ_ITEM_NUM
	CA_CD_03(I)%LENGTH_OF_STR = K
	ALLOCATE(CA_CD_03(I)%STR(K))
	DO J = 1, K
		CA_CD_03(I)%STR(J) = ALK_VER(J : J)
	END DO
END DO
CASE_CD_READ_03 => CA_CD_03

IF (ALLOCATED(CA_CD_04)) THEN
	DEALLOCATE(CA_CD_04)
END IF
ALLOCATE(CA_CD_04(CASE_CD_READ_ITEM_NUM))
K = LEN(FIL_NAM)
DO I = 1, CASE_CD_READ_ITEM_NUM
	CA_CD_04(I)%LENGTH_OF_STR = K
	ALLOCATE(CA_CD_04(I)%STR(K))
	DO J = 1, K
		CA_CD_04(I)%STR(J) = FIL_NAM(J : J)
	END DO
END DO
CASE_CD_READ_04 => CA_CD_04


CASE_FUEL_INST_FA_ITEM_NUM = 30
IF (ALLOCATED(CA_FA_01)) THEN
	DEALLOCATE(CA_FA_01)
END IF
ALLOCATE(CA_FA_01(CASE_FUEL_INST_FA_ITEM_NUM))
K = LEN(FA_NAME)
DO I = 1, CASE_FUEL_INST_FA_ITEM_NUM
	CA_FA_01(I)%LENGTH_OF_STR = K
	ALLOCATE(CA_FA_01(I)%STR(K))
	DO J = 1, K
		CA_FA_01(I)%STR(J) = FA_NAME(J : J)
	END DO
END DO
CASE_FUEL_INST_FA_01 => CA_FA_01

IF (ALLOCATED(CA_FA_02)) THEN
	DEALLOCATE(CA_FA_02)
END IF
ALLOCATE(CA_FA_02(CASE_FUEL_INST_FA_ITEM_NUM))
K = LEN(FA_ID)
DO I = 1, CASE_FUEL_INST_FA_ITEM_NUM
	CA_FA_02(I)%LENGTH_OF_STR = K
	ALLOCATE(CA_FA_02(I)%STR(K))
	DO J = 1, K
		CA_FA_02(I)%STR(J) = FA_ID(J : J)
	END DO
END DO
CASE_FUEL_INST_FA_02 => CA_FA_02

IF (ALLOCATED(CA_FA_03)) THEN
	DEALLOCATE(CA_FA_03)
END IF
ALLOCATE(CA_FA_03(CASE_FUEL_INST_FA_ITEM_NUM))
K = LEN(FA_TYPE)
DO I = 1, CASE_FUEL_INST_FA_ITEM_NUM
	CA_FA_03(I)%LENGTH_OF_STR = K
	ALLOCATE(CA_FA_03(I)%STR(K))
	DO J = 1, K
		CA_FA_03(I)%STR(J) = FA_TYPE(J : J)
	END DO
END DO
CASE_FUEL_INST_FA_03 => CA_FA_03

IF (ALLOCATED(CA_FA_04)) THEN
	DEALLOCATE(CA_FA_04)
END IF
ALLOCATE(CA_FA_04(CASE_FUEL_INST_FA_ITEM_NUM))
K = LEN(FA_I_J)
DO I = 1, CASE_FUEL_INST_FA_ITEM_NUM
	CA_FA_04(I)%LENGTH_OF_STR = K
	ALLOCATE(CA_FA_04(I)%STR(K))
	DO J = 1, K
		CA_FA_04(I)%STR(J) = FA_I_J(J : J)
	END DO
END DO
CASE_FUEL_INST_FA_04 => CA_FA_04

IF (ALLOCATED(CA_FA_05)) THEN
	DEALLOCATE(CA_FA_05)
END IF
ALLOCATE(CA_FA_05(CASE_FUEL_INST_FA_ITEM_NUM))
K = LEN(FA_PID)
DO I = 1, CASE_FUEL_INST_FA_ITEM_NUM
	CA_FA_05(I)%LENGTH_OF_STR = K
	ALLOCATE(CA_FA_05(I)%STR(K))
	DO J = 1, K
		CA_FA_05(I)%STR(J) = FA_PID(J : J)
	END DO
END DO
CASE_FUEL_INST_FA_05 => CA_FA_05

IF (ALLOCATED(CA_FA_06)) THEN
	DEALLOCATE(CA_FA_06)
END IF
ALLOCATE(CA_FA_06(CASE_FUEL_INST_FA_ITEM_NUM))
K = LEN(FA_CYC)
DO I = 1, CASE_FUEL_INST_FA_ITEM_NUM
	CA_FA_06(I)%LENGTH_OF_STR = K
	ALLOCATE(CA_FA_06(I)%STR(K))
	DO J = 1, K
		CA_FA_06(I)%STR(J) = FA_CYC(J : J)
	END DO
END DO
CASE_FUEL_INST_FA_06 => CA_FA_06

IF (ALLOCATED(CA_FA_07)) THEN
	DEALLOCATE(CA_FA_07)
END IF
ALLOCATE(CA_FA_07(CASE_FUEL_INST_FA_ITEM_NUM))
K = LEN(FA_SHL)
DO I = 1, CASE_FUEL_INST_FA_ITEM_NUM
	CA_FA_07(I)%LENGTH_OF_STR = K
	ALLOCATE(CA_FA_07(I)%STR(K))
	DO J = 1, K
		CA_FA_07(I)%STR(J) = FA_SHL(J : J)
	END DO
END DO
CASE_FUEL_INST_FA_07 => CA_FA_07

IF (ALLOCATED(CA_FA_08)) THEN
	DEALLOCATE(CA_FA_08)
END IF
ALLOCATE(CA_FA_08(CASE_FUEL_INST_FA_ITEM_NUM))
DO I = 1, CASE_FUEL_INST_FA_ITEM_NUM
	CA_FA_08(I) = FA_BUR
END DO
CASE_FUEL_INST_FA_08 => CA_FA_08

CASE_FUEL_INST_FA_09 => CASE_FUEL_INST_FA_08

IF (ALLOCATED(CA_FA_10)) THEN
	DEALLOCATE(CA_FA_10)
END IF
ALLOCATE(CA_FA_10(CASE_FUEL_INST_FA_ITEM_NUM))
DO I = 1, CASE_FUEL_INST_FA_ITEM_NUM
	CA_FA_10(I) = 500.0
END DO
CASE_FUEL_INST_FA_10 => CA_FA_10

IF (ALLOCATED(CA_FA_11)) THEN
	DEALLOCATE(CA_FA_11)
END IF
ALLOCATE(CA_FA_11(CASE_FUEL_INST_FA_ITEM_NUM))
DO I = 1, CASE_FUEL_INST_FA_ITEM_NUM
	CA_FA_11(I) = 0
END DO
CASE_FUEL_INST_FA_11 => CA_FA_11

IF (ALLOCATED(CA_FA_12)) THEN
	DEALLOCATE(CA_FA_12)
END IF
ALLOCATE(CA_FA_12(CASE_FUEL_INST_FA_ITEM_NUM))
DO I = 1, CASE_FUEL_INST_FA_ITEM_NUM
	CA_FA_12(I) = 0.0
END DO
CASE_FUEL_INST_FA_12 => CA_FA_12

IF (ALLOCATED(CA_FA_13)) THEN
	DEALLOCATE(CA_FA_13)
END IF
ALLOCATE(CA_FA_13(CASE_FUEL_INST_FA_ITEM_NUM))
DO I = 1, CASE_FUEL_INST_FA_ITEM_NUM
	CA_FA_13(I) = 12
END DO
CASE_FUEL_INST_FA_13 => CA_FA_13

CASE_FUEL_INST_FA_14 => CASE_FUEL_INST_FA_13



CA_OPT = 1
CALL OUTPUT_CASES(CASE_ID, JOB_ID, DATE_TIME, REF_TIME, REF_BU, TITLE, PTR, CA_OPT)
I = 3
CALL INSERT_RETURN(I, PTR)
CA_OPT = 2
CALL OUTPUT_CASES(CASE_ID, JOB_ID, DATE_TIME, REF_TIME, REF_BU, TITLE, PTR, CA_OPT)
I = 3
CALL INSERT_RETURN(I, PTR)
CA_OPT = 3
CALL OUTPUT_CASES(CASE_ID, JOB_ID, DATE_TIME, REF_TIME, REF_BU, TITLE, PTR, CA_OPT)


CALL OUTPUT_FULTXT(TXT_LNK_HEAD, FILEID)


CLOSE(FILEID)
CALL CLEAR_BASIC_DATA(TXT_LNK_HEAD)
CALL CLEAR_BASIC_DATA(FUEL, ARRMAC_LENGTH)
CALL CLEAR_BASIC_DATA(CROD, ARRMAC_LENGTH)
CALL CLEAR_BASIC_DATA(CRODGP, ARRMAC_LENGTH)
CALL CLEAR_BASIC_DATA(NAME_LIST, LIST_LENGTH)
CALL CLEAR_BASIC_DATA(VALUE_LIST, LIST_LENGTH)
END PROGRAM